# SPDX-License-Identifier: GPL-2.0
#
# ---------------------------------------------------------------------------

# =========================Basic lib ===========================
#
# `$(rust_flags)` is passed in case the user added `--sysroot`.
rustc_sysroot := $(shell MAKEFLAGS= $(RUSTC) $(rust_flags) --print sysroot)
rustc_host_target := $(shell $(RUSTC) --version --verbose | grep -F 'host: ' | cut -d' ' -f2)
RUST_LIB_SRC ?= $(rustc_sysroot)/lib/rustlib/src/rust/library

core-cfgs = \
    --cfg no_fp_fmt_parse

redirect-intrinsics = \
	__addsf3 __eqsf2 __extendsfdf2 __gesf2 __lesf2 __ltsf2 __mulsf3 __nesf2 __truncdfsf2 __unordsf2 \
	__adddf3 __eqdf2 __ledf2 __ltdf2 __muldf3 __unorddf2 \
	__muloti4 __multi3 \
	__udivmodti4 __udivti3 __umodti3

ifneq ($(or $(CONFIG_ARM64),$(and $(CONFIG_RISCV),$(CONFIG_64BIT))),)
	# These intrinsics are defined for ARM64 and RISCV64
	redirect-intrinsics += \
		__ashrti3 \
		__ashlti3 __lshrti3
endif

$(obj)/core.o: private skip_clippy = 1
$(obj)/core.o: private skip_flags = -Wunreachable_pub
$(obj)/core.o: private rustc_objcopy = $(foreach sym,$(redirect-intrinsics),--redefine-sym $(sym)=__rust$(sym))
$(obj)/core.o: private rustc_target_flags = $(core-cfgs)
$(obj)/core.o: $(RUST_LIB_SRC)/core/src/lib.rs \
    $(wildcard $(objtree)/include/config/RUSTC_VERSION_TEXT) FORCE
	+$(call if_changed_rule,rustc_library)

$(obj)/compiler_builtins.o: private rustc_objcopy = -w -W '__*'
$(obj)/compiler_builtins.o: $(src)/compiler_builtins.rs $(obj)/core.o FORCE
	+$(call if_changed_rule,rustc_library)


base_libs= $(obj)/core.o $(obj)/compiler_builtins.o

# ------------------------------------- const_format ------------------------
$(obj)/const_format.o: private skip_flags = -Wunreachable_pub
$(obj)/const_format.o: private rustc_target_flags = --extern const_format_proc_macros
$(obj)/const_format.o: $(src)/const_format/src/lib.rs  $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)

# ------------------------------------- static assertions ------------------------
$(obj)/static_assertions.o: private rustc_target_flags = --extern static_assertions_proc_macros
$(obj)/static_assertions.o: $(src)/static_assertions/src/lib.rs $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)


# --------------------------------------------- bitflags -------------------
$(obj)/bitflags.o: private skip_flags = -Wunreachable_pub
$(obj)/bitflags.o: $(src)/bitflags/src/lib.rs  $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)



# Ordinary directory descending
# ---------------------------------------------------------------------------
obj-y			+= core.o
obj-y			+= compiler_builtins.o
obj-y 			+= const_format.o
obj-y 			+= static_assertions.o
obj-y 			+= bitflags.o
