# SPDX-License-Identifier: GPL-2.0
#
# ---------------------------------------------------------------------------

proc_macros_prepare:
	$(Q)$(MAKE) $(build)=proc_macros prepare

# =========================Basic lib ===========================
#
# `$(rust_flags)` is passed in case the user added `--sysroot`.
rustc_sysroot := $(shell MAKEFLAGS= $(RUSTC) $(rust_flags) --print sysroot)
rustc_host_target := $(shell $(RUSTC) --version --verbose | grep -F 'host: ' | cut -d' ' -f2)
RUST_LIB_SRC ?= $(rustc_sysroot)/lib/rustlib/src/rust/library

core-cfgs = \
    --cfg no_fp_fmt_parse

redirect-intrinsics = \
	__addsf3 __eqsf2 __extendsfdf2 __gesf2 __lesf2 __ltsf2 __mulsf3 __nesf2 __truncdfsf2 __unordsf2 \
	__adddf3 __eqdf2 __ledf2 __ltdf2 __muldf3 __unorddf2 \
	__muloti4 __multi3 \
	__udivmodti4 __udivti3 __umodti3

ifneq ($(or $(CONFIG_ARM64),$(and $(CONFIG_RISCV),$(CONFIG_64BIT))),)
	# These intrinsics are defined for ARM64 and RISCV64
	redirect-intrinsics += \
		__ashrti3 \
		__ashlti3 __lshrti3
endif

$(obj)/core.o: private skip_clippy = 1
$(obj)/core.o: private skip_flags = -Wunreachable_pub
$(obj)/core.o: private rustc_objcopy = $(foreach sym,$(redirect-intrinsics),--redefine-sym $(sym)=__rust$(sym))
$(obj)/core.o: private rustc_target_flags = $(core-cfgs)
$(obj)/core.o: $(RUST_LIB_SRC)/core/src/lib.rs proc_macros_prepare \
    $(wildcard $(objtree)/include/config/RUSTC_VERSION_TEXT) FORCE
	+$(call if_changed_rule,rustc_library)

$(obj)/compiler_builtins.o: private rustc_objcopy = -w -W '__*'
$(obj)/compiler_builtins.o: $(src)/compiler_builtins.rs $(obj)/core.o FORCE
	+$(call if_changed_rule,rustc_library)


base_libs= $(obj)/core.o $(obj)/compiler_builtins.o

# ------------------------------------- const_format ------------------------
$(obj)/const_format.o: private skip_flags = -Wunreachable_pub
$(obj)/const_format.o: private rustc_target_flags = --extern const_format_proc_macros
$(obj)/const_format.o: $(src)/const_format/src/lib.rs  $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)

rusttestlib-const_format: private skip_flags = -Wunreachable_pub
rusttestlib-const_format: private rustc_target_flags = --extern const_format_proc_macros
rusttestlib-const_format: $(src)/const_format/src/lib.rs  FORCE
	+$(call if_changed,rustc_test_library)

# ------------------------------------- static assertions ------------------------
$(obj)/static_assertions.o: private rustc_target_flags = --extern static_assertions_proc_macros
$(obj)/static_assertions.o: $(src)/static_assertions-1.1.0/src/lib.rs $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)

rusttestlib-static_assertions: private rustc_target_flags = --extern static_assertions_proc_macros
rusttestlib-static_assertions: $(src)/static_assertions-1.1.0/src/lib.rs  FORCE
	+$(call if_changed,rustc_test_library)

# --------------------------------------------- bitflags -------------------
$(obj)/bitflags.o: private skip_flags = -Wunreachable_pub
$(obj)/bitflags.o: $(src)/bitflags/src/lib.rs  $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)

rusttestlib-bitflags: private skip_flags = -Wunreachable_pub
rusttestlib-bitflags: $(src)/bitflags/src/lib.rs  FORCE
	+$(call if_changed,rustc_test_library)

# ----------------------------------tock registers ------------------------
tock_cfg = --cfg 'feature="register_types"'
tock_skip_flags = -Wunreachable_pub -Wmissing_docs
tock_target_flags = $(tock_cfg) -Aelided-lifetimes-in-paths

$(obj)/tock_registers.o: private skip_flags = $(tock_skip_flags)
$(obj)/tock_registers.o: private rustc_target_flags = $(tock_target_flags)
$(obj)/tock_registers.o: $(src)/tock-registers-0.10.0/src/lib.rs  $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)

rusttestlib-tock_registers: private skip_flags = $(tock_skip_flags)
rusttestlib-tock_registers: private rustc_target_flags = $(tock_target_flags)
rusttestlib-tock_registers: $(src)/tock-registers-0.10.0/src/lib.rs  FORCE
	+$(call if_changed,rustc_test_library)


# ------------------------------- fdt ---------------------
fdt_skip_flags = -Wunreachable_pub -Wmissing_docs  -Dwarnings

$(obj)/fdtree_rs.o: $(obj)/fdtree-rs/src/lib.rs $(base_libs) FORCE
	+$(call if_changed_rule,rustc_library)
$(obj)/fdtree_rs.o: private skip_flags = $(fdt_skip_flags)

rusttestlib-fdtree_rs: private skip_flags = $(fdt_skip_flags)
rusttestlib-fdtree_rs: $(src)/fdtree-rs/src/lib.rs  FORCE
	+$(call if_changed,rustc_test_library)

# -------------------------------- rusttest libraries ---------------------

rusttest: rusttestlib-const_format rusttestlib-static_assertions \
	rusttestlib-bitflags rusttestlib-tock_registers rusttestlib-fdtree_rs 



# Ordinary directory descending
# ---------------------------------------------------------------------------
obj-y			+= core.o
obj-y			+= compiler_builtins.o
obj-y 			+= const_format.o
obj-y 			+= static_assertions.o
obj-y 			+= bitflags.o
obj-y 			+= tock_registers.o
obj-y 			+= fdtree_rs.o
